---
- name: Reload ufw
  community.general.ufw:
    state: reloaded

- name: Reload slapd-backup
  ansible.builtin.systemd_service:
    name: slapd-backup.timer
    state: restarted
    daemon_reload: true
