global:
  checkNewVersion: true
serversTransport:
  insecureSkipVerify: false
log:
  format: common
  level: INFO
accessLog:
  format: common
api:
  dashboard: true
  insecure: false
entryPoints:
  https:
    address: ":443"
  http:
    address: ":80"
  metrics:
    address: ":{{ traefik.metrics_port }}"
metrics:
  prometheus:
    entryPoint: metrics
    addRoutersLabels: true
certificatesResolvers:
  main:
    acme:
      email: hpcs-admin@hpcs.cs.tsukuba.ac.jp
      storage: /certs/acme.json
      certificatesDuration: 2160
      tlsChallenge: {}
providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true
