users:
  traefik:
    uid: 2001
  openldap:
    uid: 106
    gid: 105

authoritative_dns:
  internal_ip: 172.16.0.232
  metrics_port: 9153

resolver_dns:
  internal_ip: 172.16.0.220
  metrics_port: 8453

ldap:
  internal_ip: 172.16.0.220

node_exporter:
  version: "1.9.0"

gw:
  wan_ip: 130.158.78.241

prometheus:
  version: 3.2.1
  targets:
    - ip: 172.16.0.232
      label: node0
    - ip: 172.16.0.230
      label: node1
  uid: 4001
  gid: 4001

traefik:
  metrics_port: 9091

grafana:
  uid: 472
  gid: 472
