---
- name: Copy bastion.service
  ansible.builtin.template:
    src: bastion.service
    dest: /etc/systemd/system/bastion.service
    owner: root
    group: root
    mode: "0644"
  notify: Restart bastion

- name: Enable bastion service
  ansible.builtin.systemd_service:
    name: bastion
    daemon_reload: true
    enabled: true
    state: started

- name: Allow DNS
  community.general.ufw:
    rule: allow
    port: 10022
    proto: tcp
