---
- name: Copy node-exporter.service
  ansible.builtin.template:
    src: node-exporter.service
    dest: /etc/systemd/system/node-exporter.service
    owner: root
    group: root
    mode: "0644"
  notify: Restart node-exporter.service

- name: Enable node-exporter service
  ansible.builtin.systemd_service:
    name: node-exporter
    daemon_reload: true
    enabled: true
    state: started

- name: Allow prometheus access
  community.general.ufw:
    rule: allow
    port: 9100
    proto: tcp
  notify: Reload ufw
