- name: Restart kanidm.service
  ansible.builtin.systemd_service:
    name: kanidm
    daemon_reload: true
    enabled: true
    state: restarted

- name: Reload ufw
  community.general.ufw:
    state: reloaded
