---
- name: Reload ufw
  community.general.ufw:
    state: reloaded

- name: Restart postgres
  ansible.builtin.systemd_service:
    name: postgresql
    daemon_reload: true
    enabled: true
    state: restarted
