---
- name: Create local user home
  become: true
  ansible.builtin.file:
    state: directory
    path: /local
    owner: root
    group: root
    mode: "0755"

- name: Create rescue user
  become: true
  ansible.builtin.user:
    name: rescue
    create_home: true
    home: /local/home/rescue
    groups:
      - adm
      - admin
      - cdrom
      - wheel

- name: Set authorized_keys of rescue user
  become: true
  ansible.posix.authorized_key:
    user: rescue
    key: https://github.com/{{ item }}.keys
  loop:
    - namachan10777
    - onokatio
