---
- name: Create local user home
  become: true
  ansible.builtin.file:
    state: directory
    path: /local
    owner: root
    group: root
    mode: "0755"

- name: Create rescue user
  become: true
  ansible.builtin.user:
    name: rescue
    create_home: true
    home: /local/home/rescue
    password: "{{ rescue.pass }}"
    groups:
      - adm
      - sudo
      - cdrom
      - dip
      - plugdev
      - lxd

- name: Allow nopassword sudo for rescue
  community.general.sudoers:
    name: 99-rescue
    user: rescue
    commands: ALL
    state: present
    nopassword: true

- name: Set authorized_keys of rescue user
  become: true
  ansible.posix.authorized_key:
    user: rescue
    key: https://github.com/{{ item }}.keys
  loop:
    - namachan10777
    - onokatio
