---
- name: Intall Postgres
  ansible.builtin.apt:
    name:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2

- name: Allow postgres access fron internal nodes
  community.general.ufw:
    rule: allow
    port: 5432
    proto: tcp
  notify: Reload ufw

- name: Copy pg_hba.conf
  ansible.builtin.copy:
    src: pg_hba.conf
    dest: /etc/postgresql/16/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: "0640"
  notify: Restart postgres

- name: Copy postgresql.conf
  ansible.builtin.copy:
    src: postgresql.conf
    dest: /etc/postgresql/16/main/postgresql.conf
    owner: postgres
    group: postgres
    mode: "0644"
  notify: Restart postgres

- name: Create grafana database
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: grafana
    comment: Grafana database

- name: Create grafaba user
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    login_db: grafana
    name: grafana
    password: "{{ secrets.grafana.db.password }}"

- name: Create grafana database
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: grafana
    owner: grafana
    comment: Grafana database

- name: Enable postgres
  ansible.builtin.systemd_service:
    name: postgresql
    daemon_reload: true
    enabled: true
    state: started
