---
- name: Install OpenLDAP
  ansible.builtin.apt:
    name:
      - slapd
      - ldap-utils

- name: Copy ldap.conf
  ansible.builtin.copy:
    src: ldap.conf
    dest: /etc/ldap/ldap.conf
    owner: root
    group: root
    mode: "0644"

- name: Copy check_password.conf
  ansible.builtin.copy:
    src: check_password.conf
    dest: /etc/ldap/check_password.conf
    owner: root
    group: root
    mode: "0644"

- name: Create /etc/ldap/changes
  ansible.builtin.file:
    path: /etc/ldap/changes
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy slap initialization scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/ldap/changes/{{ item }}
    owner: root
    group: root
    mode: "0600"
  loop:
    - root_account.ldif
    - samba.ldif

- name: Start slapd service
  ansible.builtin.systemd_service:
    name: slapd
    state: started
    enabled: true
    daemon_reload: true

- name: Allow LDAP access
  community.general.ufw:
    rule: allow
    port: 389
    proto: tcp
    src: 172.16.0.0/16
  notify: Reload ufw

- name: Allow LDAPS access
  community.general.ufw:
    rule: allow
    port: 636
    proto: tcp
    src: 172.16.0.0/16
  notify: Reload ufw

- name: Create /mnt/home/backups/ldap
  ansible.builtin.file:
    state: directory
    owner: root
    group: root
    mode: "0700"
    path: /mnt/home/backups/ldap

- name: Copy slapd-backup.sh
  ansible.builtin.copy:
    src: slapd-backup.sh
    dest: /usr/local/bin/slapd-backup.sh
    owner: root
    group: root
    mode: "0755"

- name: Copy slapd-backup.service
  ansible.builtin.copy:
    src: slapd-backup.service
    dest: /etc/systemd/system/slapd-backup.service
    owner: root
    group: root
    mode: "0644"
  notify: Reload slapd-backup

- name: Copy slapd-backup.timer
  ansible.builtin.copy:
    src: slapd-backup.timer
    dest: /etc/systemd/system/slapd-backup.timer
    owner: root
    group: root
    mode: "0644"
  notify: Reload slapd-backup

- name: Enable slapd-backup.timer
  ansible.builtin.systemd_service:
    name: slapd-backup.timer
    state: started
    enabled: true
    daemon_reload: true
  notify: Reload slapd-backup
