---
- name: Install OpenSSH
  ansible.builtin.apt:
    name:
      - ssh
  notify: Restart OpenSSH

- name: Disable password authentication
  ansible.builtin.lineinfile:
    regexp: ^PasswordAuthentication .*
    line: PasswordAuthentication no
    path: /etc/ssh/sshd_config
  notify: Restart OpenSSH

- name: Start OpenSSH
  ansible.builtin.systemd_service:
    name: ssh
    enabled: true
    daemon_reload: true
    state: started
