---
- name: Install ufw and fail2ban
  ansible.builtin.apt:
    name:
      - ufw
      - fail2ban

- name: Deny from anywhere as default policy and enable UFW
  community.general.ufw:
    state: enabled
    policy: deny

- name: Allow OpenSSH Port
  community.general.ufw:
    rule: allow
    name: OpenSSH
  notify: Reload ufw

- name: Configure fail2ban
  ansible.builtin.template:
    src: sshd.conf.j2
    dest: /etc/fail2ban/jail.d/sshd.conf
    directory_mode: "0755"
    mode: "0644"
    owner: root
    group: root

- name: Start fail2ban
  ansible.builtin.systemd_service:
    name: fail2ban
    state: started
    enabled: true
    daemon_reload: true
