---
- name: Create /var/lib/traefik
  ansible.builtin.file:
    path: /var/lib/traefik
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create /var/lib/traefik/certs
  ansible.builtin.file:
    path: /var/lib/traefik/certs
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Create /etc/traefik
  ansible.builtin.file:
    path: /etc/traefik/
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create /etc/traefik/containers
  ansible.builtin.file:
    path: /etc/traefik/containers
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create /etc/traefik/containers/fallback
  ansible.builtin.file:
    path: /etc/traefik/containers/fallback
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy traefik.yaml
  ansible.builtin.template:
    src: traefik.yaml
    dest: /etc/traefik/traefik.yaml
    owner: root
    group: root
    mode: "0644"
  notify: Restart docker compose

- name: Copy fallback files
  ansible.builtin.copy:
    src: fallback/{{ item }}
    dest: /etc/traefik/containers/fallback/{{ item }}
    owner: root
    group: root
    mode: "0644"
  loop:
    - Dockerfile
    - userdir2.conf
  notify: Restart docker compose

- name: Create /etc/traefik/dynamic
  ansible.builtin.file:
    path: /etc/traefik/dynamic
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy route to cfp-summary-server
  ansible.builtin.copy:
    src: cfp-summary-server.yaml
    dest: /etc/traefik/dynamic/cfp-summary-server.yaml
    owner: root
    group: root
    mode: "0644"
  notify: Restart docker compose

- name: Create /etc/cfp_summary
  ansible.builtin.file:
    path: /etc/cfp-summary
    state: directory
    owner: root
    group: root
    mode: "0755"
  notify: Restart docker compose

- name: Copy app.json
  ansible.builtin.template:
    src: app.json
    dest: /etc/cfp-summary/app.json
    owner: root
    group: root
    mode: "0644"
  notify: Restart docker compose

- name: Copy db.json
  ansible.builtin.template:
    src: db.json
    dest: /etc/cfp-summary
    owner: root
    group: root
    mode: "0640"

- name: Create /var/lib/cfp-summary-db
  ansible.builtin.file:
    path: /var/lib/cfp-summary-db
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Copy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml
    dest: /etc/traefik/containers/docker-compose.yml
    group: root
    owner: root
    mode: "0600"
  notify: Restart docker compose

- name: Install python3-docker
  ansible.builtin.apt:
    name:
      - python3-docker
      - docker-compose

- name: Enable docker compose
  community.docker.docker_compose_v2:
    project_src: /etc/traefik/containers
    build: always
    remove_orphans: true
  notify: Restart docker compose

- name: Allow HTTP
  community.general.ufw:
    rule: allow
    port: 80
    proto: tcp
  notify: Reload ufw

- name: Allow HTTPS
  community.general.ufw:
    rule: allow
    port: 443
    proto: tcp
  notify: Reload ufw
