---
- name: Download docker repository signing key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    owner: root
    group: root
    mode: "0644"

- name: Get architecture
  ansible.builtin.command: dpkg --print-architecture
  register: host_arch
  changed_when: false

- name: Add docker repository
  ansible.builtin.apt_repository:
    filename: docker
    repo: >-
      deb
      [arch={{ host_arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/ubuntu
      {{ ansible_distribution_release }}
      stable

- name: Install docker
  ansible.builtin.apt:
    update_cache: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
