---
- name: Create rescue user
  hosts: all
  become: true
  roles:
    - rescue

- name: Setup node-expoter
  hosts: all
  become: true
  roles:
    - node_exporter

- name: Configure network
  hosts: all
  become: true
  roles:
    - ip
    - sshd
    - firewall
    - static_hosts

- name: Configure LDAP
  hosts: node0.lab.hpcs.cs.tsukuba.ac.jp
  become: true
  roles:
    - mount_nfs_home
    - slapd

- name: Configure Authoritative DNS
  hosts: node0.lab.hpcs.cs.tsukuba.ac.jp
  become: true
  roles:
    - authoritative_dns

- name: Configure Resolver DNS
  hosts: node1.lab.hpcs.cs.tsukuba.ac.jp
  become: true
  roles:
    - resolver_dns

- name: Setup bastion service
  hosts: node0.lab.hpcs.cs.tsukuba.ac.jp
  become: true
  roles:
    - bastion

- name: Install general-purpose postgres
  hosts: node1.lab.hpcs.cs.tsukuba.ac.jp
  become: true
  roles:
    - postgres

- name: Configure prometheus
  hosts: node1.lab.hpcs.cs.tsukuba.ac.jp
  become: true
  roles:
    - prometheus

- name: Setup idm service
  hosts: node0.lab.hpcs.cs.tsukuba.ac.jp
  become: true
  roles:
    - certbot
    - kanidm

- name: Web
  hosts: node1.lab.hpcs.cs.tsukuba.ac.jp
  become: true
  roles:
    - mount_nfs_home
    - web
