---
- name: Create rescue user
  hosts: all
  become: true
  roles:
    - rescue

- name: Configure network
  hosts: all
  become: true
  roles:
    - ip
    - sshd
    - firewall
    - static_hosts

- name: Configure LDAP
  hosts: node0.lab.hpcs.cs.tsukuba.ac.jp
  become: true
  roles:
    - mount_nfs_home
    - slapd

- name: Configure Authoritative DNS
  hosts: node0.lab.hpcs.cs.tsukuba.ac.jp
  become: true
  roles:
    - authoritative_dns

- name: Configure Resolver DNS
  hosts: node1.lab.hpcs.cs.tsukuba.ac.jp
  become: true
  roles:
    - resolver_dns

- name: Web
  hosts: node1.lab.hpcs.cs.tsukuba.ac.jp
  become: true
  roles:
    - mount_nfs_home
    - web
