---
- name: Install certbot
  community.general.snap:
    name: certbot
    classic: true
  notify: Restart certbot

- name: Create /etc/letsencrypt dirs
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: "0755"
    state: directory
  loop:
    - /etc/letsencrypt
    - /etc/letsencrypt/renewal
    - /etc/letsencrypt/renewal-hooks
    - /etc/letsencrypt/renewal-hooks/deploy

- name: Install nginx
  ansible.builtin.apt:
    name: nginx

- name: Enable nginx
  ansible.builtin.systemd_service:
    name: nginx
    daemon_reload: true
    enabled: true
    state: started

- name: Allow 80 port
  community.general.ufw:
    rule: allow
    port: 80
    proto: tcp
  notify: Reload ufw

- name: Enable certbot
  ansible.builtin.systemd_service:
    name: snap.certbot.renew.timer
    daemon_reload: true
    enabled: true
    state: started
