name: ansible-lint
on:
  pull_request:
    branches: ["main"]
  push:
  workflow_dispatch:
defaults:
  run:
    working-directory: ansible
jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Setup venv
        run: |
          uv sync
          source .venv/bin/activate
          echo "$VIRTUAL_ENV/bin" >> "$GITHUB_PATH"

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          args: ""
          setup_python: "false"
          working_directory: "ansible"
          requirements_file: ""
