---
- name: Restart bastion
  ansible.builtin.systemd_service:
    name: coredns
    daemon_reload: true
    enabled: true
    state: restarted

- name: Reload ufw
  community.general.ufw:
    state: reloaded
